### ISSUE TITLE
fetch请求后有个小问题

### ISSUE THREAD

**Issue by kukujbb** [github1586/nuxt-bnhcp#13]
请求数据成功 network 是有看到返回数据的，但是我想用一个data接收数据打印出来却发现这个data是没有成功的？？？ 弄了一下午，不是很熟悉。。。谢谢
![8oj t0mx3w10il7 d5lpbb](https://user-images.githubusercontent.com/20284294/32941648-6a9bb4c4-cbc1-11e7-8369-9b02a07b5f8c.png)
![ugh4 181c q r rn80 3](https://user-images.githubusercontent.com/20284294/32941646-67e10f90-cbc1-11e7-8a60-b2eed7e92c75.png)
![9_ uytir p mqup f p gt](https://user-images.githubusercontent.com/20284294/32941656-6fafa5ec-cbc1-11e7-8434-f8c6a110403a.png)
![dfsm 16ub42 9j4c_ s 1y](https://user-images.githubusercontent.com/20284294/32941662-72aac0ba-cbc1-11e7-8b4c-651f0d099805.png)

**Comment by github1586** [comment]
@kukujbb filterVideo在哪里调用的？

**Comment by kukujbb** [comment]
@github1586 是通过点击触发的 更多的时候是提示这个错误
我也挺纳闷的。。。emmmm
![2](https://user-images.githubusercontent.com/20284294/33007795-4df47558-ce0b-11e7-8056-762b345e74f7.png)
![1](https://user-images.githubusercontent.com/20284294/33007802-501218b8-ce0b-11e7-8e49-c7430a1430ce.png)

**Comment by github1586** [comment]
@kukujbb 没有结束的大括号嘛？

**Comment by liyueS777** [comment]
为什么你要在点击事件的函数 filterVideo 前面加 async？这样是有什么好处吗

**Comment by liyueS777** [comment]
你这边通过nuxt框架 部署到服务器的时候，有没有做 访问ip 或者域名的配置，我这边开了一个虚拟机，外网还不能访问那个虚拟机的Ip对应项目
