### ISSUE TITLE
local template 下面，npm install Ok ,npm run dev报错Unhandled promise rejection 

### ISSUE THREAD

**Issue by hanwsscan** [github1586/nuxt-bnhcp#15]
$ npm run dev

> bnhcp@1.0.0 dev E:\qtx\nuxt-bnhcp\local\template
> backpack dev

 DONE  Compiled successfully in 938ms10:23:08

(node:1984) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_1_nuxt___default.a is not a constructor

node v6.11.2
请帮忙看看咋回事

**Comment by github1586** [comment]
@hanwsscan 卸载node_moduels 清楚模块缓存    用yarn重新安装下

**Comment by mngogo** [comment]
(node:62461) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_1_nuxt___default.a is not a constructor
^C%

无用，重复后仍然不行。 在template里面yarn install  ， npm run dev , 或nuxt build  都不行

**Comment by keenjaan** [comment]
@mngogo 我也是一样的报错，换node版本，重装包都没用，别人的项目能正常运行，就这个不行。

**Comment by mngogo** [comment]
谢谢告知。  估计是作者git rollback 操作过，
