### ISSUE TITLE
浏览器回退不刷新

### ISSUE THREAD

**Issue by wkh2** [github1586/nuxt-bnhcp#18]
您好，我遇到一个问题，在当前项目中点击链接跳转走，当点击浏览器回退按钮回到当前项目的时候，发现页面并没有刷新，您有解决方案吗？

**Comment by aikefang** [comment]
这种问题应该是数据缓存没有做好，你检查下代码。

**Comment by fiamma21** [comment]
设置fetch的cache试试

**Comment by hoshimiyawasure** [comment]
推荐使用 useAsyncData 进行数据请求更加适合ssr场景：
const { data: blogList } = await useAsyncData("blogList", async () => {
  try {
    const res = await $fetch("/api/blog-list");
    console.log("获取博客列表成功:", res);
    return res;
  } catch (error) {
    console.error("获取博客列表失败:", error);
    return [];
  }
});
useAsyncData(“blogList”)中“blogList”是作为useAsyncData()方法传入的第二个参数方法中return返回的本次请求结果数据的唯一标识，
作用：
缓存去重：如果在同一个应用中多次调用 useAsyncData 且 Key 相同，Nuxt 只会执行一次请求，后续调用直接复用结果。
Payload 传输：在服务端渲染完成后，Nuxt 会将这个 Key 对应的数据序列化并注入到 HTML 中，传递给客户端，确保客户端不需要重新请求。
注意：Key 必须是全局唯一的。如果在一个列表中循环调用，通常需要使用动态 Key（如 useAsyncData(\blog- $ {id}, ...)`）。

**Comment by liyueS777** [comment]
这是来自QQ邮箱的假期自动回复邮件
