### ISSUE TITLE
npm run dev报错运行不起来

### ISSUE THREAD

**Issue by xihadandan** [github1586/nuxt-bnhcp#24]
D:\2git-work\node-server-work\nuxt-bnhcp\node_modules\mini-css-extract-plugin\dist\index.js:20
  util: { createHash }
          ^

TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.

**Comment by xihadandan** [comment]
npm install已经安装了包

**Comment by Zeus-Iqd** [comment]
@xihadandan 改成yarn install 就好了

**Comment by chengwenxin** [comment]
项目跑不起来 yarn install  也有各种错误

**Comment by github1586** [comment]
@chengwenxin 什么错误

**Comment by Ancient-Ares** [comment]
升级一下webpack 就可以了

**Comment by yiibase** [comment]
████████████████████ 10% building modules[BABEL] Note: The code generator has deoptimised the styling of "/Volumes/vim/share/pinta/.nuxt/App.js" as it exceeds the max of "500KB".

**Comment by yiibase** [comment]
yarn install 出错████████████████████ 10% building modules[BABEL] Note: The code generator has deoptimised the styling of "/Volumes/vim/share/bnhcp/.nuxt/App.js" as it exceeds the max of "500KB".

**Comment by github1586** [comment]
@yiibase yarn dev 试试

**Comment by yiibase** [comment]
> @yiibase yarn dev 试试
一样的，请问能正常打包的具体环境（含版本）是 ？

**Comment by github1586** [comment]
@yiibase 
node 版本 v8.9.1
yarn 版本 1.3.2
mac系统 
刚才试了一下可以的 yarn dev

**Comment by yiibase** [comment]
> @yiibase
> node 版本 v8.9.1
> yarn 版本 1.3.2
> mac系统
> 刚才试了一下可以的 yarn dev

您文件都没传完，敷衍的回答。虽然打包出错至少我贴出.babelrc文件，帮看看
{
  "presets": ["es-2015","stage-2"],
    "plugins": [
        ["transform-runtime", {
          "helpers": false,
          "polyfill": false,
          "regenerator": true,
          "moduleName": "babel-runtime"

        }]
    ],
      "compact": false
  }

**Comment by github1586** [comment]
@yiibase  项目的所有前后台文件 都已提交。

**Comment by yiibase** [comment]
> @yiibase 项目的所有前后台文件 都已提交。
nuxt/dist/文件夹没有
