### ISSUE TITLE
请教，如果后端接口是java写的，那我该如何改造

### ISSUE THREAD

**Issue by xijin** [github1586/nuxt-bnhcp#28]
首先感谢大大开源的代码，启发良多。
现在我是在做一个vue2.x项目升级，需要进行首屏优化，之前是ajax json形式的接口，
利用nuxt 这一套的话，服务端部分该如何进行改造比较合适，即：asyncData部分调之前的接口而不是express的

**Comment by github1586** [comment]
@xijin 服务端是独立存在  直接提供api地址接口就可以

**Comment by xijin** [comment]
@github1586 需要在服务端渲染的请求接口，写在asyncData里面就可以了，对于旧项目，我是通过配置nuxt.config.js 里面的proxy实现的。
但是在客户端发起的ajax请求，proxy拦截不到。不知道这个是怎么解决的呢

**Comment by xijin** [comment]
已解决，我想错了。使用axios的话，根本不需要用到proxy，只需要配置baseURL，指向新页面即可
