### ISSUE TITLE
本地运行 sql文件 缺少course表

### ISSUE THREAD

**Issue by Ancient-Ares** [github1586/nuxt-bnhcp#30]
SELECT i.institutionsName,e.gradeId,w.gradeTwoId,t.teacherName,t.evalPerson, p.campusesName, c.*,
        date_format(open_date,'%Y-%m-%d') open_date1, 
        date_format(end_date,'%Y-%m-%d') end_date1 
        from course c 
        left join teacher t  on c.teacher_id = t.thacherId
        left join campuses p  on t.schoolId = p.campusesId
        left join institutions i  on p.campusesParentId = i.institutionsId
        left join gradeThree h on c.course_id = h.gradeThreeId
        left join gradeTwo w on h.pid = w.gradeTwoId
        left join gradeOne e on w.pid = e.gradeId
        where e.gradeId=15963591 
        ORDER BY RAND()
        limit 0,15

=> `Table 'bnhcp.course' doesn't exist`

**Comment by github1586** [comment]
@Ancient-Ares 抽时间 我重新上传一份

**Comment by txl910514** [comment]
对 好久能上传一份 就那个表少了

**Comment by txl910514** [comment]
@github1586  user 表也少了

**Comment by github1586** [comment]
表都上传了
