### ISSUE TITLE
yarn dev报错

### ISSUE THREAD

**Issue by main2018** [github1586/nuxt-bnhcp#31]
Plugin 0 specified in "F:\\Vue\\nuxt-bnhcp-master\\node_modules\\@nuxtjs\\babel-preset-app\\index.js" provided an invalid property of "default" (While processing preset: "F:\\Vue\\nuxt-bnhcp-master\\node_modules\\@nuxtjs\\babel-preset-app\\index.js")

**Comment by main2018** [comment]
已解决，yarn版本太低，升级到最新重新install下就好了

**Comment by github1586** [comment]
嗯嗯

main <notifications@github.com> 于2019年5月7日周二 上午9:50写道：
