### ISSUE TITLE
sql没上传最新的吧，少表

### ISSUE THREAD

**Issue by HiSun001** [github1586/nuxt-bnhcp#41]
Table 'bnhcp.course' doesn't exist
Table 'bnhcp.user' doesn't exist

**Comment by github1586** [comment]
是最新的哦

**Comment by github1586** [comment]
根目录的sql

**Comment by github1586** [comment]
@HiSun001

**Comment by chending1994** [comment]
sqlMessage: "Table 'bnhcp.course' doesn't exist"
我运行也是少表额
